### ISSUE TITLE
Support or integrate with Rocksdb statebackend?

### ISSUE THREAD

**Issue by kant777** [HeartSaVioR/spark-state-tool#30]
Support or integrate with [Rocksdb statebackend](https://github.com/chermenin/spark-states)?

**Comment by HeartSaVioR** [comment]
Thanks for the interest!

The project doesn't depend on the state store implementation, as the project only uses the state store "interface". I wouldn't mention specific implementations on the support list - it would make the cost of the maintenance very high.

Hopefully @redsk is playing this project with RocksDB state backend (@chermenin) so let's watch the test result of #33. (You can enable notification on the PR.)

Thanks again. Closing.
