### ISSUE TITLE
StateStoreReaderRDD very slow reading the state

### ISSUE THREAD

**Issue by redsk** [HeartSaVioR/spark-state-tool#35]
A state of roughly 300000 records whose schema is similar to (sorry, can't give full details)
```scala
case class State(
  s1: String,
  s2: String,
  s3: String,
  b1: Boolean,
  i1: Int,
  l1: Long,
  ss1: Set[String],
  si1: Set[Long],
  t1: Timestamp,
  t2: Timestamp,
  sd1: Set[Date],
)
```
takes 37 minutes to be read on a cluster with 
```
driver: 4 cores @ 24 Gb ram
4 executors: 8 cores @ 16 Gb ram
```
which is way too long. 
My [hacky code](https://github.com/chermenin/spark-states/issues/15#issuecomment-629574930) that I posted in `spark-states` issue takes just a few seconds.

I think the problem is in 
```scala
object StateStoreRelation {
  def unifyStateRowPair(schema: StructType)(pair: (UnsafeRow, UnsafeRow)): Row = {
    val row = new GenericInternalRow(2)
    row.update(0, pair._1)
    row.update(1, pair._2)

    val encoder: ExpressionEncoder[Row] = RowEncoder(schema).resolveAndBind()
    encoder.fromRow(row)
  }
}
```
that you use as:
```scala
  override def buildScan(): RDD[Row] = {
   ...

    val rdd = new StateStoreReaderRDD(session, keySchema, valueSchema,
      resolvedCpLocation, batchId, operatorId, storeName)
    rdd.map(StateStoreRelation.unifyStateRowPair(schema))
  }
```

I think you're creating an `Encoder` for every Row(in the `.map`). I'm testing my assumption and I'll create a PR soon if this is the case. 

Also, in `StateStoreReaderRDD.scala` you do 
```scala
val iter = store.iterator().map(pair => (pair.key, pair.value))
```
So one `.map` here, and one in 
```scala
    rdd.map(StateStoreRelation.unifyStateRowPair(schema))
```
Why not returning an `RDD[Row]` directly from `StateStoreReaderRDD` instead?

**Comment by redsk** [comment]
Yes, that was it. This code
```scala
    val rdd = new StateStoreReaderRDD(session, keySchema, valueSchema,
      resolvedCpLocation, batchId, operatorId, storeName)
    val encoder = RowEncoder(schema).resolveAndBind()
    rdd.map { pair =>
      val row = new GenericInternalRow(2)
      row.update(0, pair._1)
      row.update(1, pair._2)
      encoder.fromRow(row)
    }
```
takes 1 second to execute while the original one took 40 minutes.
I'll send a PR to fix this bug shortly

**Comment by HeartSaVioR** [comment]
Ah great nice finding! Honestly I was focused on functionality while implementing and haven't had time to do performance/scalability tests. I'm feeling lucky to have you who can evaluate and even investigate the issue :) Thanks for your time!

**Comment by HeartSaVioR** [comment]
> Why not returning an RDD[Row] directly from StateStoreReaderRDD instead?

I'd like to make `StateStoreReaderRDD` just do read from the state and provide the same, in case the class can be used for multiple purposes. Looks like it's OK to provide `Iterator[UnsafeRowPair]` instead of `Iterator[(UnsafeRow, UnsafeRow)]` for `StateStoreReaderRDD.compute()` to avoid creating tuples.

**Comment by redsk** [comment]
I've created a PR for this issue, I think we can move the discussion there. #36
